# Generated by Django 4.2.7 on 2023-12-04 21:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='people.person')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', utils.models.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('content', models.TextField()),
                ('role', models.CharField(choices=[('Assistant', 'Assistant'), ('Person', 'Person')])),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chat')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', utils.models.Manager()),
            ],
        ),
    ]
