# Generated by Django 4.2.7 on 2023-12-04 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistant', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_goals', to='people.person'),
        ),
        migrations.AddField(
            model_name='goal',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='assistant.goal'),
        ),
        migrations.AddField(
            model_name='goal',
            name='properties',
            field=models.ManyToManyField(related_name='goals', through='assistant.Record', to='assistant.property'),
        ),
        migrations.AddField(
            model_name='entity',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_entities', to='people.person'),
        ),
        migrations.AddField(
            model_name='entity',
            name='type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities', to='assistant.entitytype'),
        ),
        migrations.AddField(
            model_name='effect',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='assistant.entity'),
        ),
        migrations.AddField(
            model_name='effect',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='assistant.goal'),
        ),
        migrations.AddField(
            model_name='dependency',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='assistant.goal'),
        ),
        migrations.AddField(
            model_name='dependency',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='assistant.goal'),
        ),
    ]
